name: BetterBoard
version: ${project.version}
main: me.hsgamer.betterboard.BetterBoard
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - MiniPlaceholders
  - ViaVersion
authors: [ HSGamer ]
folia-supported: true
